# tinapple mkinitcpio configuration
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt lvm2 filesystems keyboard fsck)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19 -T0)
MODULES=(btrfs crc32c libcrc32c)
