# tinapple Limine configuration
timeout: 5
default_entry: tinapple-lts

:tinapple-lts
    protocol: linux
    kernel_path: boot/vmlinuz-linux-lts
    cmdline: root=UUID=@ROOT_UUID@ rw quiet splash loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0
    module_path: boot/initramfs-linux-lts.img

:tinapple-lts-fallback
    protocol: linux
    kernel_path: boot/vmlinuz-linux-lts
    cmdline: root=UUID=@ROOT_UUID@ rw single
    module_path: boot/initramfs-linux-lts-fallback.img

:UEFI Shell v2
    protocol: efi
    path: EFI/shellx64_v2.efi

:UEFI Shell v1
    protocol: efi
    path: EFI/shellx64_v1.efi
