# /etc/pacman.conf for tinapple ISO build

[options]
Architecture = auto
ParallelDownloads = 10
Color
ILoveCandy
CheckSpace
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[cachyos-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-core-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-extra-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[tinapple]
SigLevel = Never
Server = file:///mnt/shared/projects/tinapple/tinapple-repo/repo/$arch
