package store

import "time"

func DefaultCatalog() *Repository {
	return &Repository{
		Source:      "tinapple-official",
		LastUpdated: time.Now(),
		Apps: []App{
			// System
			{
				ID:           "foot",
				Name:         "Foot Terminal",
				Description:  "Fast, lightweight and minimalist Wayland/X11 terminal emulator",
				Category:     "System",
				Version:      "1.20.2",
				Maintainer:   "tinapple Team",
				PackageName:  "foot",
				InstallCmd:   "pacman -S --noconfirm foot",
				UninstallCmd: "pacman -R --noconfirm foot",
				Tags:         []string{"terminal", "lightweight", "default"},
				Icon:         "󰞷",
				Size:         1500000,
				Homepage:     "https://codeberg.org/dnkl/foot",
				License:      "MIT",
			},
			{
				ID:           "chadwm",
				Name:         "Chadwm Window Manager",
				Description:  "Blazing fast, customizable dynamic tiling window manager for tinapple",
				Category:     "System",
				Version:      "0.0.1",
				Maintainer:   "tinapple Team",
				PackageName:  "tinapple-chadwm",
				InstallCmd:   "pacman -S --noconfirm tinapple-chadwm",
				UninstallCmd: "pacman -R --noconfirm tinapple-chadwm",
				Tags:         []string{"wm", "tiling", "desktop"},
				Icon:         "🪟",
				Size:         3200000,
				Homepage:     "https://github.com/tinapple/tinapple-chadwm",
				License:      "MIT",
			},
			{
				ID:           "btop",
				Name:         "btop++",
				Description:  "Resource monitor that shows usage and stats for processor, memory, disks, network and processes",
				Category:     "System",
				Version:      "1.4.0",
				Maintainer:   "Arch Linux",
				PackageName:  "btop",
				InstallCmd:   "pacman -S --noconfirm btop",
				UninstallCmd: "pacman -R --noconfirm btop",
				Tags:         []string{"monitor", "cli", "htop"},
				Icon:         "📊",
				Size:         2400000,
				Homepage:     "https://github.com/aristocratos/btop",
				License:      "Apache-2.0",
			},
			{
				ID:           "fastfetch",
				Name:         "Fastfetch",
				Description:  "Like neofetch, but much faster because written mainly in C",
				Category:     "System",
				Version:      "2.29.0",
				Maintainer:   "Arch Linux",
				PackageName:  "fastfetch",
				InstallCmd:   "pacman -S --noconfirm fastfetch",
				UninstallCmd: "pacman -R --noconfirm fastfetch",
				Tags:         []string{"system", "fetch", "info"},
				Icon:         "🍎",
				Size:         1800000,
				Homepage:     "https://github.com/fastfetch-cli/fastfetch",
				License:      "MIT",
			},

			// Development
			{
				ID:           "neovim",
				Name:         "Neovim",
				Description:  "Vim-fork focused on extensibility and usability",
				Category:     "Development",
				Version:      "0.10.4",
				Maintainer:   "Arch Linux",
				PackageName:  "neovim",
				InstallCmd:   "pacman -S --noconfirm neovim",
				UninstallCmd: "pacman -R --noconfirm neovim",
				Tags:         []string{"editor", "vim", "code"},
				Icon:         "📝",
				Size:         28000000,
				Homepage:     "https://neovim.io",
				License:      "Apache-2.0",
			},
			{
				ID:           "docker",
				Name:         "Docker Engine",
				Description:  "Pack, ship and run any application as a lightweight container",
				Category:     "Development",
				Version:      "27.3.1",
				Maintainer:   "Arch Linux",
				PackageName:  "docker",
				InstallCmd:   "pacman -S --noconfirm docker && systemctl enable docker",
				UninstallCmd: "pacman -R --noconfirm docker",
				Tags:         []string{"containers", "virtualization", "server"},
				Icon:         "🐳",
				Size:         85000000,
				Homepage:     "https://www.docker.com",
				License:      "Apache-2.0",
			},
			{
				ID:           "git",
				Name:         "Git VCS",
				Description:  "Fast, scalable, distributed revision control system",
				Category:     "Development",
				Version:      "2.48.1",
				Maintainer:   "Arch Linux",
				PackageName:  "git",
				InstallCmd:   "pacman -S --noconfirm git",
				UninstallCmd: "pacman -R --noconfirm git",
				Tags:         []string{"vcs", "code", "git"},
				Icon:         "🌱",
				Size:         35000000,
				Homepage:     "https://git-scm.com",
				License:      "GPL-2.0",
			},

			// Media
			{
				ID:           "jellyfin",
				Name:         "Jellyfin Media Server",
				Description:  "The Free Software Media System that puts you in control of your media",
				Category:     "Media",
				Version:      "10.9.11",
				Maintainer:   "tinapple Team",
				PackageName:  "jellyfin-server",
				InstallCmd:   "pacman -S --noconfirm jellyfin-server jellyfin-web && systemctl enable jellyfin",
				UninstallCmd: "pacman -R --noconfirm jellyfin-server jellyfin-web",
				Tags:         []string{"streaming", "movies", "homelab"},
				Icon:         "🎬",
				Size:         120000000,
				Homepage:     "https://jellyfin.org",
				License:      "GPL-2.0",
			},
			{
				ID:           "navidrome",
				Name:         "Navidrome Music Server",
				Description:  "Modern Music Server and Streamer compatible with Subsonic/Madsonic",
				Category:     "Media",
				Version:      "0.53.3",
				Maintainer:   "Arch Linux",
				PackageName:  "navidrome",
				InstallCmd:   "pacman -S --noconfirm navidrome && systemctl enable navidrome",
				UninstallCmd: "pacman -R --noconfirm navidrome",
				Tags:         []string{"music", "audio", "subsonic"},
				Icon:         "🎵",
				Size:         45000000,
				Homepage:     "https://www.navidrome.org",
				License:      "GPL-3.0",
			},

			// Network
			{
				ID:           "tailscale",
				Name:         "Tailscale Mesh VPN",
				Description:  "Zero config VPN based on WireGuard for secure cross-device access",
				Category:     "Network",
				Version:      "1.76.6",
				Maintainer:   "Arch Linux",
				PackageName:  "tailscale",
				InstallCmd:   "pacman -S --noconfirm tailscale && systemctl enable tailscaled",
				UninstallCmd: "pacman -R --noconfirm tailscale",
				Tags:         []string{"vpn", "wireguard", "mesh", "networking"},
				Icon:         "🌐",
				Size:         42000000,
				Homepage:     "https://tailscale.com",
				License:      "BSD-3-Clause",
			},
			{
				ID:           "wireguard",
				Name:         "WireGuard Tools",
				Description:  "Extremely simple yet fast and modern VPN networking tools",
				Category:     "Network",
				Version:      "1.0.20210914",
				Maintainer:   "Arch Linux",
				PackageName:  "wireguard-tools",
				InstallCmd:   "pacman -S --noconfirm wireguard-tools",
				UninstallCmd: "pacman -R --noconfirm wireguard-tools",
				Tags:         []string{"vpn", "crypto", "tunnel"},
				Icon:         "🛡️",
				Size:         350000,
				Homepage:     "https://www.wireguard.com",
				License:      "GPL-2.0",
			},
			{
				ID:           "tinapple-nginx",
				Name:         "Tinapple Nginx Proxy",
				Description:  "Preconfigured high-performance reverse proxy for homelab services",
				Category:     "Network",
				Version:      "0.0.1",
				Maintainer:   "tinapple Team",
				PackageName:  "tinapple-nginx",
				InstallCmd:   "pacman -S --noconfirm tinapple-nginx && systemctl enable tinapple-nginx",
				UninstallCmd: "pacman -R --noconfirm tinapple-nginx",
				Tags:         []string{"proxy", "nginx", "web"},
				Icon:         "🌐",
				Size:         500000,
				Homepage:     "https://github.com/tinapple/tinapple-nginx",
				License:      "MIT",
			},

			// Storage & Backups
			{
				ID:           "syncthing",
				Name:         "Syncthing",
				Description:  "Continuous decentralized file synchronization program",
				Category:     "Storage & Backups",
				Version:      "1.27.12",
				Maintainer:   "Arch Linux",
				PackageName:  "syncthing",
				InstallCmd:   "pacman -S --noconfirm syncthing && systemctl enable syncthing@admin",
				UninstallCmd: "pacman -R --noconfirm syncthing",
				Tags:         []string{"sync", "backup", "files"},
				Icon:         "🔄",
				Size:         25000000,
				Homepage:     "https://syncthing.net",
				License:      "MPL-2.0",
			},
			{
				ID:           "restic",
				Name:         "Restic Backup",
				Description:  "Fast, secure, efficient backup program supporting local and cloud remotes",
				Category:     "Storage & Backups",
				Version:      "0.17.3",
				Maintainer:   "Arch Linux",
				PackageName:  "restic",
				InstallCmd:   "pacman -S --noconfirm restic",
				UninstallCmd: "pacman -R --noconfirm restic",
				Tags:         []string{"backup", "encryption", "snapshots"},
				Icon:         "💾",
				Size:         28000000,
				Homepage:     "https://restic.net",
				License:      "BSD-2-Clause",
			},
			{
				ID:           "qbittorrent-nox",
				Name:         "qBittorrent NoX",
				Description:  "Headless torrent client with feature-rich Web UI",
				Category:     "Storage & Backups",
				Version:      "5.0.2",
				Maintainer:   "Arch Linux",
				PackageName:  "qbittorrent-nox",
				InstallCmd:   "pacman -S --noconfirm qbittorrent-nox",
				UninstallCmd: "pacman -R --noconfirm qbittorrent-nox",
				Tags:         []string{"downloads", "p2p", "torrents"},
				Icon:         "📥",
				Size:         38000000,
				Homepage:     "https://www.qbittorrent.org",
				License:      "GPL-2.0",
			},

			// Remote Desktop (Task R4)
			{
				ID:           "xrdp",
				Name:         "xrdp Remote Desktop (RDP)",
				Description:  "Open source Remote Desktop Protocol (RDP) server with chadwm integration",
				Category:     "Remote Desktop",
				Version:      "0.10.2",
				Maintainer:   "Arch Linux",
				PackageName:  "xrdp",
				InstallCmd:   "pacman -S --noconfirm xrdp && systemctl enable xrdp xrdp-sesman",
				UninstallCmd: "pacman -R --noconfirm xrdp",
				Tags:         []string{"remote", "rdp", "desktop", "chadwm"},
				Icon:         "🖥️",
				Size:         4500000,
				Homepage:     "http://www.xrdp.org",
				License:      "Apache-2.0",
			},
			{
				ID:           "tigervnc",
				Name:         "TigerVNC Server",
				Description:  "High-performance, platform-neutral implementation of VNC for remote desktop",
				Category:     "Remote Desktop",
				Version:      "1.14.1",
				Maintainer:   "Arch Linux",
				PackageName:  "tigervnc",
				InstallCmd:   "pacman -S --noconfirm tigervnc",
				UninstallCmd: "pacman -R --noconfirm tigervnc",
				Tags:         []string{"vnc", "remote", "desktop"},
				Icon:         "📺",
				Size:         5800000,
				Homepage:     "https://tigervnc.org",
				License:      "GPL-2.0",
			},
		},
	}
}
