title    tinapple OS live (%ARCH%, UEFI, fallback initramfs)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts-fallback.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=1G console=ttyS0,115200 console=tty0 quiet splash loglevel=3
