package manifest

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// KnownServiceDefaultPorts maps popular homelab services to their standard ports.
var KnownServiceDefaultPorts = map[string]int{
	"jellyfin":     8096,
	"qbittorrent":  8080,
	"syncthing":    8384,
	"dash":         8088,
	"plex":         32400,
	"sonarr":       8989,
	"radarr":       7878,
	"prowlarr":     9696,
	"bazarr":       6767,
	"transmission": 9091,
	"prometheus":   9090,
	"grafana":      3000,
	"vaultwarden":  8000,
}

// LoadManifest loads and parses a YAML manifest from a file.
func LoadManifest(filePath string) (*Manifest, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read manifest file '%s': %w", filePath, err)
	}
	return ParseManifest(data)
}

// ParseManifest parses YAML data into a Manifest struct.
func ParseManifest(data []byte) (*Manifest, error) {
	var m Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("failed to unmarshal manifest YAML: %w", err)
	}

	// Apply sensible port defaults for services if not explicitly configured
	for name, svc := range m.Services {
		if svc.Port == 0 {
			if defPort, ok := KnownServiceDefaultPorts[name]; ok {
				svc.Port = defPort
				m.Services[name] = svc
			}
		}
	}

	return &m, nil
}

// SaveManifest writes the Manifest struct to a file as YAML.
func SaveManifest(filePath string, m *Manifest) error {
	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("failed to serialize manifest to YAML: %w", err)
	}
	if err := os.WriteFile(filePath, data, 0644); err != nil {
		return fmt.Errorf("failed to write manifest to '%s': %w", filePath, err)
	}
	return nil
}

// GenerateConfigs generates service configurations from the manifest.
// This is a stub implementation - full implementation would use Go templates.
func GenerateConfigs(m *Manifest, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}
	
	// Generate Caddy config
	caddyConfig := generateCaddyConfig(m)
	caddyPath := outputDir + "/Caddyfile"
	if err := os.WriteFile(caddyPath, []byte(caddyConfig), 0644); err != nil {
		return fmt.Errorf("failed to write Caddyfile: %w", err)
	}
	
	// Generate systemd service overrides
	for name, svc := range m.Services {
		if svc.Enabled {
			override := generateSystemdOverride(name, svc)
			overridePath := outputDir + "/" + name + ".override.conf"
			if err := os.WriteFile(overridePath, []byte(override), 0644); err != nil {
				return fmt.Errorf("failed to write %s override: %w", name, err)
			}
		}
	}
	
	// Generate network config
	networkConfig := generateNetworkConfig(m)
	networkPath := outputDir + "/network.conf"
	if err := os.WriteFile(networkPath, []byte(networkConfig), 0644); err != nil {
		return fmt.Errorf("failed to write network.conf: %w", err)
	}
	
	return nil
}

func generateCaddyConfig(m *Manifest) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by tinapple-config-generator\n")
	sb.WriteString("# DO NOT EDIT MANUALLY\n\n")
	
	sb.WriteString("{\n")
	sb.WriteString("    admin off\n")
	sb.WriteString("    auto_https disable_redirects\n")
	sb.WriteString("}\n\n")
	
	// Dashboard
	if svc, ok := m.Services["dash"]; ok && svc.Enabled {
		port := svc.Port
		if port == 0 {
			port = 8088
		}
		sb.WriteString(fmt.Sprintf(":%d {\n", port))
		sb.WriteString("    reverse_proxy localhost:8088\n")
		sb.WriteString("}\n\n")
	}
	
	// Jellyfin
	if svc, ok := m.Services["jellyfin"]; ok && svc.Enabled {
		port := svc.Port
		if port == 0 {
			port = 8096
		}
		sb.WriteString(fmt.Sprintf("jellyfin.%s {\n", m.Hostname))
		sb.WriteString(fmt.Sprintf("    reverse_proxy localhost:%d\n", port))
		sb.WriteString("}\n\n")
	}
	
	// qBittorrent
	if svc, ok := m.Services["qbittorrent"]; ok && svc.Enabled {
		port := svc.Port
		if port == 0 {
			port = 8080
		}
		sb.WriteString(fmt.Sprintf("qbittorrent.%s {\n", m.Hostname))
		sb.WriteString(fmt.Sprintf("    reverse_proxy localhost:%d\n", port))
		sb.WriteString("}\n\n")
	}
	
	return sb.String()
}

func generateSystemdOverride(name string, svc ServiceConfig) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Auto-generated override for %s\n", name))
	sb.WriteString("[Service]\n")
	
	if svc.User != "" {
		sb.WriteString(fmt.Sprintf("User=%s\n", svc.User))
		sb.WriteString(fmt.Sprintf("Group=%s\n", svc.User))
	}
	
	for k, v := range svc.Overrides {
		sb.WriteString(fmt.Sprintf("Environment=%s=%s\n", k, v))
	}
	
	return sb.String()
}

func generateNetworkConfig(m *Manifest) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated network config\n")
	sb.WriteString("[Network]\n")
	sb.WriteString(fmt.Sprintf("Interface=%s\n", m.Network.Interface))
	
	if m.Network.DHCP {
		sb.WriteString("DHCP=yes\n")
	} else if m.Network.StaticFallback != nil {
		sf := m.Network.StaticFallback
		sb.WriteString(fmt.Sprintf("Address=%s\n", sf.Address))
		sb.WriteString(fmt.Sprintf("Gateway=%s\n", sf.Gateway))
		for _, dns := range sf.DNS {
			sb.WriteString(fmt.Sprintf("DNS=%s\n", dns))
		}
	}
	
	return sb.String()
}
