post_install() {
  systemctl enable tailscaled.service >/dev/null 2>&1 || true
  systemctl enable wg-quick@wg0.service >/dev/null 2>&1 || true
  systemctl enable pihole-FTL.service >/dev/null 2>&1 || true
  systemctl enable unbound.service >/dev/null 2>&1 || true
}

post_upgrade() { post_install; }

pre_remove() {
  systemctl disable tailscaled.service >/dev/null 2>&1 || true
  systemctl disable wg-quick@wg0.service >/dev/null 2>&1 || true
  systemctl disable pihole-FTL.service >/dev/null 2>&1 || true
  systemctl disable unbound.service >/dev/null 2>&1 || true
}
